### ISSUE TITLE
Any pre-trained model which I can try out?

### ISSUE THREAD

**Issue by flyfy1** [tqbl/arca23k-baseline#3]
I'm trying to do audio classification on my existing audio recordings.

However, I'm new to ML world, and I want to find some pretrained model which can try out first. Is there certain pre-trained model params, which I can simply test them out?

**Comment by tqbl** [comment]
Hi. I currently don't have access to a pretrained version of the arca23k-baseline model, but I'll see if I can do something about that and update you if so.

If you're fine with any pretrained model for audio classification, you can try PANNs.
Download models from here: https://zenodo.org/record/3987831/
Code: https://github.com/qiuqiangkong/audioset_tagging_cnn

**Comment by tqbl** [comment]
I'm assuming the PANN model is sufficient and am closing the issue for now.
